apiVersion: v1
kind: Namespace
metadata:
  name: flux-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: fluxcd-community
  namespace: flux-system
spec:
  interval: 24h
  url: https://fluxcd-community.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-image-reflector
  namespace: flux-system
spec:
  interval: 10m
  chart:
    spec:
      chart: flux2
      version: '>=2.10.0'
      sourceRef:
        kind: HelmRepository
        name: fluxcd-community
      interval: 12h
  values:
    imageReflectorController:
      create: true
      serviceAccount:
        annotations:
          eks.amazonaws.com/role-arn: "arn:aws:iam::428941813349:role/pong-image-reflector"
    imageAutomationController:
      create: true
    # Disable other controllers (already installed)
    helmController:
      create: false
    kustomizeController:
      create: false
    notificationController:
      create: false
    sourceController:
      create: false
