apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pong-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./iac/kubernetes/manifests/overlays/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
  - apiVersion: apps/v1
    kind: Deployment
    name: pong-backend
    namespace: pong
  - apiVersion: apps/v1
    kind: Deployment
    name: pong-centrifugo
    namespace: pong
  - apiVersion: v1
    kind: Service
    name: pong-backend
    namespace: pong
  - apiVersion: v1
    kind: Service
    name: pong-centrifugo
    namespace: pong
